export type Job = {
  id: string
  title: string
  company: string
  location: string
  workplaceModel: "Onsite"|"Hybrid"|"Remote"
  employmentType: "Intern"|"Full-time"|"Contract"
  experienceLevel: "Fresh Grad"|"Junior"|"Mid"
  salaryMin?: number
  salaryMax?: number
  datePosted: string // ISO
  description: string
  skills: string[]
  visaEligible: boolean
}

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Software Engineer (Full-Stack)",
    company: "Grab",
    location: "Singapore",
    workplaceModel: "Hybrid",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    salaryMin: 6500,
    salaryMax: 9500,
    datePosted: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Work on scalable services across React, Node.js, and Go.",
    skills: ["React", "Node.js", "TypeScript", "AWS", "Docker"],
    visaEligible: true,
  },
  {
    id: "2",
    title: "Data Analyst",
    company: "Shopee",
    location: "Singapore",
    workplaceModel: "Onsite",
    employmentType: "Full-time",
    experienceLevel: "Junior",
    salaryMin: 4500,
    salaryMax: 6500,
    datePosted: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Analyze marketplace data and build dashboards.",
    skills: ["SQL", "Python", "Tableau", "PowerBI"],
    visaEligible: false,
  },
  {
    id: "3",
    title: "Backend Engineer (Node.js)",
    company: "Sea Group",
    location: "Singapore",
    workplaceModel: "Hybrid",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    salaryMin: 7000,
    salaryMax: 10000,
    datePosted: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Build microservices with Node.js and PostgreSQL.",
    skills: ["Node.js", "PostgreSQL", "Redis", "Kubernetes"],
    visaEligible: true,
  },
  {
    id: "4",
    title: "Frontend Developer (React)",
    company: "GovTech",
    location: "Singapore",
    workplaceModel: "Hybrid",
    employmentType: "Contract",
    experienceLevel: "Junior",
    salaryMin: 5000,
    salaryMax: 7000,
    datePosted: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Develop citizen-facing applications with React and Tailwind.",
    skills: ["React", "TailwindCSS", "TypeScript"],
    visaEligible: false,
  },
  {
    id: "5",
    title: "Machine Learning Engineer",
    company: "ByteDance",
    location: "Singapore",
    workplaceModel: "Onsite",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    salaryMin: 9000,
    salaryMax: 13000,
    datePosted: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Deploy ML models and optimize inference performance.",
    skills: ["Python", "TensorFlow", "PyTorch", "AWS"],
    visaEligible: true,
  },
  {
    id: "6",
    title: "Business Intelligence Analyst",
    company: "DBS Bank",
    location: "Singapore",
    workplaceModel: "Hybrid",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    salaryMin: 6000,
    salaryMax: 8500,
    datePosted: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Support analytics initiatives across risk and finance.",
    skills: ["SQL", "PowerBI", "Python", "Azure"],
    visaEligible: false,
  },
  {
    id: "7",
    title: "Software Engineer Intern",
    company: "NCS",
    location: "Singapore",
    workplaceModel: "Onsite",
    employmentType: "Intern",
    experienceLevel: "Fresh Grad",
    salaryMin: 1200,
    salaryMax: 1800,
    datePosted: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Assist in feature development and QA.",
    skills: ["Java", "Spring Boot", "SQL"],
    visaEligible: false,
  },
  {
    id: "8",
    title: "Data Engineer",
    company: "Carousell",
    location: "Singapore",
    workplaceModel: "Hybrid",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    salaryMin: 8000,
    salaryMax: 11000,
    datePosted: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Build data pipelines and manage warehousing.",
    skills: ["Python", "Airflow", "Spark", "BigQuery"],
    visaEligible: true,
  },
  {
    id: "9",
    title: "Product Data Analyst",
    company: "Lazada",
    location: "Singapore",
    workplaceModel: "Hybrid",
    employmentType: "Full-time",
    experienceLevel: "Junior",
    salaryMin: 5000,
    salaryMax: 7000,
    datePosted: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Partner with PMs to drive data-informed decisions.",
    skills: ["SQL", "R", "Python", "Tableau"],
    visaEligible: false,
  },
  {
    id: "10",
    title: "Cloud Engineer",
    company: "GovTech",
    location: "Singapore",
    workplaceModel: "Hybrid",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    salaryMin: 7800,
    salaryMax: 10500,
    datePosted: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Manage infrastructure on AWS and Azure.",
    skills: ["AWS", "Azure", "Terraform", "Docker"],
    visaEligible: false,
  },
  {
    id: "11",
    title: "Frontend Engineer (Next.js)",
    company: "ShopBack",
    location: "Singapore",
    workplaceModel: "Remote",
    employmentType: "Full-time",
    experienceLevel: "Mid",
    salaryMin: 7200,
    salaryMax: 9800,
    datePosted: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Build performant web apps with Next.js.",
    skills: ["React", "Next.js", "TypeScript", "GraphQL"],
    visaEligible: true,
  },
  {
    id: "12",
    title: "Junior Software Engineer",
    company: "ST Engineering",
    location: "Singapore",
    workplaceModel: "Onsite",
    employmentType: "Full-time",
    experienceLevel: "Junior",
    salaryMin: 4200,
    salaryMax: 6000,
    datePosted: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
    description: "Support system development and testing.",
    skills: ["Java", "React", "SQL", "Linux"],
    visaEligible: false,
  },
]
